name: Testing NPM Caching
on: workflow_dispatch

jobs:
    node-build-cache:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Yarn
              uses: actions/setup-node@v3
              with:
                cache: 'yarn'
                cache-dependency-path: yarn.lock

            - name: Build Project
              run: yarn install
            
            #- name: Test Project
            #  run: npm test